version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0  # Specify the Java version here
    working_directory: ~/repo

    steps:
      - checkout

      # Setup Maven environment (optional, if caching is needed)
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
      # Run Maven build
      - run: mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build